### ISSUE TITLE
[30/03/2016] Teste Unitário

### ISSUE THREAD

**Issue by shonorio** [CocoaHeadsBrasil/equinociOS#1]
Escrever sobre como realizar teste unitário com para testar consumo de REST API.

**Comment by brunokoga** [comment]
@shonorio seria legal a gente já ir colocando as datas da publicação, no título da issue.

**Comment by brunokoga** [comment]
@shonorio tentei te adicionar como Assignee mas não consegui. Você consegue?

**Comment by gfpoliva** [comment]
@shonorio Você havia trocado de data com alguém? Dia 20 esta batendo com o @rabc. Depois dêem uma olhada nisso e alterem no readme

**Comment by Viniciuscarvalho** [comment]
@shonorio Ainda vai publicar o seu artigo cara?

**Comment by shonorio** [comment]
Não
