### ISSUE TITLE
Agradecimentos projeto equinociOS

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/equinociOS#114]
- Todos os autores estão convidados a deixar uma mensagem do que achou do projeto;
- A mensagem não deve ser muito grande, um texto de no máximo 250 caracteres, por exemplo;

```
- Nome
- Twitter
- Texto de agradecimento
- Link pro artigo
```

**Comment by unnamedd** [comment]
Thiago Holanda

**Comment by unnamedd** [comment]
Nome: _Thiago Holanda_
Twitter: _@tholanda_
Artigo: _http://equinocios.com/open-source/2016/03/20/backend-usando-swift-sim-e-possivel/_
Texto: _Gostaria de agradecer imensamente a cada um dos leitores que puderam nos dar a oportunidade de tocar projeto como o EquinociOS. A cada um que leu, comentou, corrigiu, aprendeu e ensinou, esse é o meu MUITO OBRIGADO por todo o suporte. Que essa seja a primeira de muitas temporadas do EquinociOS._

**Comment by rdgborges** [comment]
Nome: Rodrigo Borges Soares
Twitter: @rdgborges
Artigo: http://equinocios.com/ios/2016/03/09/layouts-adaptativos-com-uicollectionview-autolayout-e-size-classes/

Muito obrigado a todos da comunidade iOS do Brasil que ajudaram no sucesso do EquinociOS! Foi um exemplo sensacional de que quando uma comunidade se junta, projetos de muita qualidade podem surgir! Vida longa ao EquinociOS e a todas as outras iniciativas da nossa comunidade que já existem ou ainda vão existir!

**Comment by renatosarro** [comment]
Nome: Renato Matos
Twitter: rmatos_
Artigo: http://equinocios.com/extensions/2016/03/27/app-extension-today-widget/

O EquinociOS foi um acontecimento épico! Gostaria de agradecer a comunidade, leitores e autores, pela oportunidade de participar, contribuir e principalmente aprender com variadas experiências em diferentes áreas. É só o começo e espero que este projeto continue continuando continuada e continuamente!
Carry on!

**Comment by rabc** [comment]
Nome: Ricardo Borelli
Tiwtter: @rabc
Artigo: http://equinocios.com/devlife/2016/03/19/a-vida-de-um-desenvolvedor-indie/

Foi muito bom ver como a comunidade iOS cresceu tanto em número quanto em qualidade através desse EquinociOS, há tempos não via um conteúdo tão bom. Parabéns a todos os escritores e obrigado aos leitores pelo prestígio, espero que os posts sirvam de incentivo e ajuda a muitos de vocês.

**Comment by fpg1503** [comment]
**Nome:** Francesco Perrotti-Garcia
**Twitter:** [@fpg1503](https://twitter.com/fpg1503)
**Artigo:** http://equinocios.com/optionals/2016/03/25/optionals-e-o-gato-de-schrodinger/
**Texto:** Muito obrigado a todos da comunidade iOS! O EquinociOS foi sensacional e trouxe artigos de altíssimo nível sobre os mais diversos temas! Acho excelente iniciativas desse tipo que trazem conteúdo de qualidade em português para que todos da comunidade BR consigamos aproveitar! Isso tudo não seria possível sem a contribuição de todos os autores e o feedback dos leitores. Parabéns a todos!

**Comment by Viniciuscarvalho** [comment]
Nome: _Vinicius Carvalho Marques_
Twitter: _@viniciusc70_
Artigo: _http://equinocios.com/collectionview/2016/03/03/collectionview-uma-nova-abordagem-de-tableviews/_

Queria agradecer ao Solli Honorio por ter lançado o desafio pra galera no iOSDevBr e que bom que a aceitação foi muito boa. Sensacional ter uma gama de excelentes artigos com conteúdo em português e isso servirá como base de estudos durante um bom tempo. Que esse seja o primeiro de muitos equinociOS e outros projetos desses da comunidade iOS no Brasil! Muito obrigado!

Episódio do podcast do CH sobre o equinociOS -> https://soundcloud.com/cocoaheadsbr/s02e08-equinocios

**Comment by brunogb** [comment]
Nome: Bruno Gondim Bilescky
Twitter: @bgondim 
Artigo: http://equinocios.com/functional/2016/03/15/generic-functional-reactive-post/

Texto: Foi realmente muito gratificador ver todo esse envolvimento da comunidade, com todos se cobrando e se ajudando, para que este evento fosse o sucesso que foi! Parabéns para todos os envolvidos!

**Comment by marcelofabri** [comment]
Nome: Marcelo Fabri
Twitter: @marcelofabri_
Artigo: http://equinocios.com/open-source/2016/03/01/o-mundo-e-mais-que-seu-umbigo/
Texto: Parabéns para todo mundo envolvido com o projeto! Foi uma honra ter aberto o equinociOS e com certeza atingimos todos objetivos: produzir conteúdo BR para a comunidade iOS, a fortalecendo cada vez mais. É apenas [o primeiro de muitos](https://www.youtube.com/watch?v=3c17ODkNv1Q) projetos que vem por aí!

**Comment by diogot** [comment]
Nome: Diogo Tridapalli
Twitter: @diogot
Artigo: http://equinocios.com/arquitetura/2016/03/08/minimizando-acoplamento-view-e-viewcontrollers/
Texto: Estou muito feliz com a velocidade que a comunidade iOS atingiu a maturidade para produzir um projeto como esse. Em 2014 isso era inimaginável, estou muito curioso para ver o que vai acontecer nos próximos dois anos. Parabéns a todos!

**Comment by emilianoeloi** [comment]
Nome: Emiliano Elói S. Barbosa
Twitter: @emilianoeloi
Artigo: http://equinocios.com/webview/2016/03/13/webview-a-porta-de-entrada-para-desenvolvedores-web/
Texto: Agradeço Solli pela inciativa do projeto que celebra o Equinócio e a todos os membros da comunidade do CocoaHeads que prontamente absorveram a sugestão e em poucos dias já deixaram tudo preparado para um mês de artigos. Pra mim foi um privilégio.

**Comment by nobre84** [comment]
Nome: Rafael Nobre Rocha
Twitter: @nobre84
Artigo: http://equinocios.com/storyboards/2016/03/07/desmistificando-storyboards/
Texto: Gostaria de parabenizar e agradecer a todos os participantes - seja lendo, escrevendo, comentando, compartilhando - do projeto equinociOS! Foi um período muito intenso de aprendizado e amadurecimento para todos os envolvidos!

**Comment by gfpoliva** [comment]
Nome: Gabriel Oliva
Twitter: @gabrieloliva_
Artigo: http://equinocios.com/ibeacon/2016/03/18/ibeacon/

Foi uma honra fazer parte de um projeto desse porte e apoiado por tanto desenvolvedores bons! Esse foi o primeiro passo pra fazer a comunidade iOS brasileira mais forte, mais unida e produzindo conteúdo de altíssima qualidade. Well done mates!

**Comment by fabio-nogueira-almeida** [comment]
Nome: Fábio Nogueira de Almeida
Twitter: @fabintk
Artigo: http://equinocios.com/ios/2016/03/24/fastlane/
Texto: Infelizmente apenas consegui interagir com o pessoal no finalzinho do projeto, mas a experiência foi muito boa. Fico feliz em ter ajudado de alguma forma a comunidade iOS BR e parabenizo os autores dos artigos publicados. Foi um mês de muito aprendizado de qualidade.

**Comment by ythecombinator** [comment]
Nome: Matheus Albuquerque Brasil
Twitter: @mabrasil_io
Artigo: http://equinocios.com/swift/2016/03/28/swift-in-the-sky-with-types/
Texto: É incrível, com tão pouco tempo de iOS, ter a oportunidade de interagir com dezenas de pessoas da comunidade: se eu tinha dúvidas sobre a maturidade desta, o projeto equinociOS me mostrou do que ela capaz - e sou grato a todos os envolvidos por isso!

**Comment by delarge77** [comment]
Nome: Alessandro dos Santos Pinto
Twitter: @andydelarge
Artigo: http://equinocios.com/reactive/2016/03/29/Reactivecocoa-+-MVVM/
Texto: Realmente impressionante! Só me resta agradecer pela oportunidade de ter participado de um projeto incrível como esse. Compartilhar é a melhor forma de receber conhecimento. Agradeço imensamente a todos os envolvidos, e vida longa ao EquinociOS!

**Comment by loloop** [comment]
Nome: Mauricio Cardozo
Twitter: **@theloloop**
Artigo: http://equinocios.com/gamedev/2016/03/11/Unity3DeoMundoApple/

Texto: Foi fantástico não só ver mas também ter participado e contribuído para esta iniciativa da comunidade. Aprendi muito lendo os artigos do projeto, e escrevendo o meu próprio também. Muito obrigado a todos os que leram e escreveram e que venham os próximos equinociOS!

**Comment by luksfarris** [comment]
Nome: Lucas Farris
Twitter: @luksfarris
Artigo: http://equinocios.com/tutorial/2016/03/04/scenekit-overview/
Texto: Adorei a oportunidade! Foi muito bom pra praticar a escrita de artigos simples e objetivos. Obrigado a todos pela participação, e a todo o feedback.

**Comment by gsampaio** [comment]
Nome: Guilherme Martinez Sampaio
Twitter: [@gsampaio](https://twitter.com/gsampaio)
Artigo: http://equinocios.com/frameworks/2016/03/26/criando-frameworks/
Texto: Foi lindo ver a comunidade brasileira junta para escrever textos de altíssima qualidade! Me sinto muito orgulhoso de ter feito parte do equinociOS e espero ver a comunidade nacional cada vez mais unida em ideias como esta!

**Comment by lourenco-marinho** [comment]
Nome: Lourenço Pinheiro Marinho
Twitter: [@lopima](https://twitter.com/lopima)
Artigo: http://equinocios.com/ios/2016/03/16/protocol-oriented-programming/

Texto: Participar dessa iniciativa foi uma oportunidade única, pois temos uma forma de expor nossas ideais e ajudar no crescimento da comunidade iOS no Brasil! Outras iniciativas como essa são essenciais para o crescimento contínuo da nossa comunidade :D

**Comment by brunokoga** [comment]
Nome: Bruno Koga
Twitter: [@brunokoga](https://twitter.com/brunokoga)
Artigo: http://equinocios.com/2016/03/14/rxswift-como-eu-vim-parar-aqui/
Texto: O equinociOS é mais uma prova de que a comunidade iOS no Brasil amadureceu muito nos últimos meses. Tenho certeza que muitos outros projetos nascerão inspirados no equinóciOS. Parabéns ao CocoaHeads Brasil e a todos que de alguma forma participaram na publicação dos artigos!

**Comment by talesp** [comment]
Nome: Tales Pinheiro de Andrade
Twitter: @talesp
Artigo: http://equinocios.com/xcode/2016/03/10/vamos-falar-de-xcode/
Texto: Conheci a idéia do projeto via @shonorio na época que participei - rapidamente - da comunidade SP Perl Mongers. Quando ele propôs fazermos na comunidade iOS, não pensei duas vezes: tínhamos que fazer! A comunidade rapidamente se organizou, e o projeto foi um sucesso! A comunidade nacional está madura, colaborativa e integrada. Parabéns a todos os envolvidos, mal espero o que vem por aí!

**Comment by fwigorcferreira** [comment]
**Nome:** Igor Ferreira
**Twitter:** [@icastanheda](https://twitter.com/icastanheda)
**Artigo:** [http://equinocios.com/library/2016/03/17/bibliotecas/](http://equinocios.com/library/2016/03/17/bibliotecas/)

**Texto:** É muito legal ver isso acontecendo, brasileiros se reunindo para publicar ótimos conteúdos em pt-BR para a comunidade de iOS. Tenho certeza que são textos que ajudarão muitas pessoas! Mas, é uma iniciativa que cresce a comunidade e mostra que podemos construir coisas MUITO sensacionais.

**Comment by dbonates** [comment]
Nome: Daniel Bonates
Twitter: @danielbonates
Artigo 1: http://equinocios.com/ios/2016/03/02/ios-web-e-json-sem-dependencias/
Artigo 2: http://equinocios.com/ios/2016/03/21/visual-format/
Texto: EquinociOS deu certo! Tenho orgulho pela oportunidade de participar e acompanhar de perto como os nossos melhores do iOS pensam e resolvem seus problemas. A todos que participaram, escrevendo ou consumindo, organizando ou corrigindo, meu super obrigado!

**Comment by igorcferreira** [comment]
**Nome:** Igor Ferreira
**Twitter:** [@icastanheda](https://twitter.com/icastanheda)
**Artigo:** [http://equinocios.com/library/2016/03/17/bibliotecas/](http://equinocios.com/library/2016/03/17/bibliotecas/)

Texto: É muito legal ver isso acontecendo, brasileiros se reunindo para publicar ótimos conteúdos em pt-BR para a comunidade de iOS. Tenho certeza que são textos que ajudarão muitas pessoas! Mas, é uma iniciativa que cresce a comunidade e mostra que podemos construir coisas MUITO sensacionais.

**Comment by diegoventura** [comment]
Nome: Diego Ventura
Twitter: @venturadiego
Artigo: http://equinocios.com/regex/2016/03/12/o-que-sao-expressoes-regulares/

Texto: Obrigado a todos que leram, se envolveram e se interessaram pelo EquinociOS. É muito bom poder compartilhar com a comunidade um pouco do que eu aprendi pela comunidade. Foi um prazer escrever o artigo e um prazer ainda maior participar desta iniciativa visando criar ótimos conteúdos em nosso bom português para a comunidade iOS. Essa foi mais um prova de que, juntos, sempre vamos mais longe! Obrigado!

**Comment by DougFischer** [comment]
Nome: Douglas Fischer
Twitter: @DougDiskin
Artigo: http://equinocios.com/open-source/2016/03/06/uikeycommand-teclas-de-atalho-dentro-do-seu-app/

Texto: Foi excelente ver a comunidade nacional conseguir movimentar um projeto tão bacana tão rapidamente. Da idéia até a execução foram apenas poucos dias. Um grande orgulho! O CocoaHeads tem evoluído dos encontros regionais para grandes ações em conjunto, contemplando participantes de todo o mundo, indo muito além das barreiras geográficas. Vale lembrar que essa iniciativa já está rendendo frutos. Em breve teremos uma curadoria de artigos em um Medium específico do CocoaHeads Br. Você já pode ir nos seguindo por lá: https://medium.com/cocoaheads-br ;) Até a próxima!
