### ISSUE TITLE
[15/03/2017] Metaprogramação para o resto de nós

### ISSUE THREAD

**Issue by fpg1503** [CocoaHeadsBrasil/equinociOS#119]
| *TBD* | |
-- | --
*Descrição sucinta do artigo* | TBD (provavelmente meta programação)
*Data de publicação* | 15/03/2017

**Comment by unnamedd** [comment]
@fpg1503 não seria interessante colocar um título longo também ?

**Comment by fpg1503** [comment]
Assim que eu tiver certeza absoluta eu atualizo mas tem 85% de chance de ser sobre meta-programming

**Comment by unnamedd** [comment]
Boa!!!

**Comment by unnamedd** [comment]
Vai rolar um Sourcery aí ?! :P

**Comment by fpg1503** [comment]
👍🔮🎩

**Comment by dbonates** [comment]
nice! quase marquei sobre isso :)
