### ISSUE TITLE
[20/03/2017] Garimpando UIView desmistificando o Core Animation

### ISSUE THREAD

**Issue by renatosarro** [CocoaHeadsBrasil/equinociOS#121]
Um olhar profundo por tudo o que uma UIVIew possui e o que pode oferecer através de layers, masks, bezier paths etc e como aproveitar os recursos a nosso favor, trabalhando com animações.

**Comment by fpg1503** [comment]
@renatosarro Obrigado por sua contribuição!
Feito no #184, #186, #187 e #189
