### ISSUE TITLE
[24/03/2017] Sincronização de dados com CloudKit

### ISSUE THREAD

**Issue by insidegui** [CocoaHeadsBrasil/equinociOS#127]
CloudKit é uma tecnologia da Apple pouco utilizada e até um pouco "misteriosa". Pretendo fazer um artigo explicando o que é o CloudKit, para que serve de verdade e como fazer uma sincronização de dados robusta usando a API.

**Comment by fpg1503** [comment]
@insidegui Obrigado por sua contribuição!
Feito no #183.
