### ISSUE TITLE
[13/03/2017] Introdução e casos de uso: Map, Filter e Reduce.

### ISSUE THREAD

**Issue by ezefranca** [CocoaHeadsBrasil/equinociOS#131]
Uma introdução as funções map, filter e reduce com casos lúdicos e abordagem um pouco mais simples e muito mais prática, exemplificando com casos de uso para o dia-a-dia.

**Comment by ezefranca** [comment]
#149

**Comment by ezefranca** [comment]
Desculpe o atraso pessoal :(

**Comment by fpg1503** [comment]
Dado que esse acabou subindo no dia 13 o que acontece com o #118?

**Comment by fpg1503** [comment]
Se ele for terminado e alguém não conseguir terminar ele fica de reserva, vou fechar essa Issue, obrigado pela sua contribuição, @ezefranca!
