### ISSUE TITLE
[17/03/2017] Enums pra você e pro seu código

### ISSUE THREAD

**Issue by dbonates** [CocoaHeadsBrasil/equinociOS#132]
A ideia é mostrar desde o uso básico até os super powers dos Enums em Swift. Como usar esse recurso aprimorado pode deixar seu código mais seguro, estável e compreensivo. Vou avançar com um estudo de caso real e comum em quase todo app, começando com a abordagem mais simplória até chegar na simples, porém sofisticada solução só evoluindo o uso do `enum`.

**Comment by fpg1503** [comment]
@dbonates Obrigado por sua contribuição!
Feito no #179, #181, #182.
