### ISSUE TITLE
[29/03/2017] Interfaces Assíncronas com AssyncDisplayKit

### ISSUE THREAD

**Issue by gugaoliveira** [CocoaHeadsBrasil/equinociOS#134]
Abordarei o desenvolvimento de interfaces assíncronas com a library AssyncDisplayKit usada pelo Pinterest entre outros

**Comment by Viniciuscarvalho** [comment]
Ficou faltando a data @gugaoliveira!

**Comment by fpg1503** [comment]
Feito no #194. Muito obrigado por sua contribuição!
