### ISSUE TITLE
[28/03/2017] - Adotando Handoff em apps iOS e macOS

### ISSUE THREAD

**Issue by rafaelnobrepd** [CocoaHeadsBrasil/equinociOS#135]
Vou abordar as experiências que venho tendo com adoção de Handoff - The Good, the Bad and the Ugly.

**Comment by Viniciuscarvalho** [comment]
Vai escrever ainda @rafaelnobrepd ?

**Comment by nobre84** [comment]
@Viniciuscarvalho Sim, vou mandar o PR hoje
