### ISSUE TITLE
[02/03/2016] iOS nativo - load e parse de json da web sem framework de terceiros

### ISSUE THREAD

**Issue by dbonates** [CocoaHeadsBrasil/equinociOS#14]
### Assuntos abordados:
- uso de frameworks externos, quando?
- conexão e dados da web
- serialização / json -> model
- generics
- protocolos

**Comment by Viniciuscarvalho** [comment]
Depois coloca uma data no post @dbonates :+1:

**Comment by shonorio** [comment]
Material publicado http://equinocios.com/ios/2016/03/02/ios-web-e-json-sem-dependencias/
