### ISSUE TITLE
[19/03/2017] Server-side: características de um servidor

### ISSUE THREAD

**Issue by ronflima** [CocoaHeadsBrasil/equinociOS#144]
O que o seu software precisa fazer para integrar-se bem aos sistemas unix e linux. Este artigo descreve algumas características que seu software pode ter para torná-lo mais eficiente, eficaz e mais bem integrado aos principais sistemas operacionais de servidor do mercado.

**Comment by fpg1503** [comment]
@ronflima Obrigado por sua contribuição!
Feito no #176 e #188
