### ISSUE TITLE
[03/03/16] CollectionView: Uma nova abordagem de TableViews?

### ISSUE THREAD

**Issue by Viniciuscarvalho** [CocoaHeadsBrasil/equinociOS#15]
**Assuntos que serão abordados:**
- O que é uma CollectionView;
- Como funciona;
- Utilização em diversos aplicativos;
- Elementos de uma CollectionView;
  e muito mais.

**Comment by iTSangarDEV** [comment]
No trecho:

> Como na UITableView, a UICollectionView é uma subclasse de UISrollView que gerencia todos os artigos e elementos encomendados. Os itens são geridos por uma fonte de dados, que fornece uma visão celular representado po um determinado caminho de índice.

~~corrigir a palavra `po` por `por`~~

**Edit:** resolvido no PR #44
