### ISSUE TITLE
[10/03/2016] Vamos falar de Xcode

### ISSUE THREAD

**Issue by talesp** [CocoaHeadsBrasil/equinociOS#18]

**Comment by Viniciuscarvalho** [comment]
Depois coloca uma data do post @talesp :D

**Comment by talesp** [comment]
done, @Viniciuscarvalho :)

**Comment by Viniciuscarvalho** [comment]
Show viu @talesp :+1:

**Comment by gfpoliva** [comment]
@talesp Se o #83 for aceito, troca o nome da issue pelo nome do artigo que foi publicado e fecha! :D

**Comment by talesp** [comment]
titulo atualizado, post publicado, fechando issue :D
