### ISSUE TITLE
[24/03/2016] Fastlane

### ISSUE THREAD

**Issue by luiz-brasil** [CocoaHeadsBrasil/equinociOS#23]
O título será atualizado.
- Economia de horas nos processos de distribuição de aplicativos.

**Comment by gfpoliva** [comment]
@betodr Podemos contar com seu artigo?

**Comment by marcelofabri** [comment]
@betodr precisamos de uma definição. Se não ouvirmos nenhuma novidade até amanhã (21/03) no fim da tarde, seremos forçados a tirar você da agenda.

**Comment by gfpoliva** [comment]
Conversei com o @betodr e ele não se encontra mais disponível para escrever um artigo. A data 24/03 está reaberta! :D
