### ISSUE TITLE
[22/03/2016] Implementando o Facebook iOS SDK

### ISSUE THREAD

**Issue by gabrielribeiro** [CocoaHeadsBrasil/equinociOS#25]
A intenção desse artigo é ensinar a integrar o Facebook SDK em projetos iOS utilizando Swift.
A motivação do tema é pela inexistência de exemplos de integração do Facebook SDK em Swift, a quantidade de atualizações do Facebook SDK que acontecem com frequência e tornam obsoletos as integrações já realizadas no passado e a importância da utilização do Facebook SDK para o sucesso de um aplicativo.
Os tópicos abordados serão:
Login com Facebook
Permissões de acesso a dados pelo GraphAPI
Invite: convites de download do seu aplicativo enviados para as notificações dos amigos
Share: compartilhamento de conteúdo de dentro do seu app para o Facebook
Send: envio de conteúdo de dentro do seu app para o Facebook Messenger
O Parse não será abordado pois o Facebook anunciou a descontinuação do mesmo para 2017.

**Comment by gabrielribeiro** [comment]
Fui aprovado?
Ou vou pro dia extra?
Vlw!

**Comment by gfpoliva** [comment]
@gabrielribeiro vamos fazer no dia extra, o artigo do @DougFischer já estava no dia 06 no readme, só esqueceu de atualizar na issue. Se não for no dia extra, vamos colocar no lugar de algum que atrasou/ficou incompleto!

**Comment by gabrielribeiro** [comment]
OK!
Obrigado!

**Comment by gfpoliva** [comment]
Atualizei a issue e o readme com a data do dia 22. Tranquilo pra você, @gabrielribeiro?

**Comment by gabrielribeiro** [comment]
Tranquilo! Desculpe a demora em responder!
Em breve subo!

**Comment by marcelofabri** [comment]
@gabrielribeiro como anda o artigo?

**Comment by gabrielribeiro** [comment]
Galera, não segui a recomendação #1 de adiantar meu artigo e tive atrasos com a aprovação do meu app pelo Facebook (não basta sofrer só com a Apple).
Será enviado para revisão a tarde!
Desculpem!

**Comment by unnamedd** [comment]
Será enviado para revisão ? Eu achei que fosse enviado já para publicação! =/

**Comment by gfpoliva** [comment]
@gabrielribeiro cara, você tem um horário pra fazer esse PR? Não podemos quebrar essa corrente que está ativa desde o dia 1.

**Comment by unnamedd** [comment]
Por falta de iteração com os organizadores do projeto e por não cumprir com o compromisso assumido na data, estou fechando essa issue e cedendo a data a outro usuario.
