### ISSUE TITLE
21/03/2016: Resolvendo UI complexas com Auto Layout usando a linguagem Visual Format

### ISSUE THREAD

**Issue by dbonates** [CocoaHeadsBrasil/equinociOS#26]
O objetivos e abordagens:
- Auto Layout com a linguagem Visual Format
- desmistificar esse temido tópico;
- demonstrar a facilidade de para criar layouts complexos;
- cobrindo múltiplas resoluções de tela usando uma única implementação;

**Comment by gfpoliva** [comment]
Closed by #88.
