### ISSUE TITLE
[28/03/2016] Swift in the sky with types

### ISSUE THREAD

**Issue by ythecombinator** [CocoaHeadsBrasil/equinociOS#29]
Neste post serão abordados aspectos interessantes no sistema de tipos de Swift, levando em conta ideias importantes de design de linguagens de programação. Em suma, abordarei:
- _Correctness-by-Design_
- A importância do sistema de tipos de uma linguagem
- Benefícios da tipagem estática
- Inferência de tipos
- Tipagem forte & Segurança de tipos
- Eventuais pontos extras

**Comment by marcelofabri** [comment]
sugestão de tópico: phantom types :ghost:

**Comment by ythecombinator** [comment]
Haha @marcelofabri, também acho válido. Ainda vou ver melhor o público-alvo e tentar direcionar mais os temas, mas concordo :smile:

**Comment by ythecombinator** [comment]
Post em andamento, amanhã submeto o _PR_ :smile_cat:

**Comment by nobre84** [comment]
Fixed in #106
