### ISSUE TITLE
[23/03/2016] Introdução sobre Runtime em Objective-C

### ISSUE THREAD

**Issue by fggeraissate** [CocoaHeadsBrasil/equinociOS#30]
O artigo irá abordar:
- conceitos gerais
- prós e contras
- casos em que é utilizado
- como implementar

**Comment by gfpoliva** [comment]
@fggeraissate depois escolhe a data do teu artigo! :smile:

**Comment by fggeraissate** [comment]
sim, farei isso logo!! xD

Edited: pronto!

**Comment by nobre84** [comment]
Fixed in #94
