### ISSUE TITLE
[25/03/2016] Optionals e o Gato de Schrödinger

### ISSUE THREAD

**Issue by fpg1503** [CocoaHeadsBrasil/equinociOS#36]
O artigo irá abordar:
- O que são `Optional`s
- Como são implementados
- Quais são as boas práticas para usá-los
- Como se relacionam com nulablidade em Objective-C

**Comment by brunokoga** [comment]
- Optionals?
- Optionals!

**Comment by nobre84** [comment]
@fpg1503 Como está seu artigo pra amanhã ?

**Comment by fpg1503** [comment]
No #99

**Comment by nobre84** [comment]
Fixed in #99
