### ISSUE TITLE
[27/03/2016] App Extensions - Today Notification

### ISSUE THREAD

**Issue by renatosarro** [CocoaHeadsBrasil/equinociOS#42]
Introdução ao Application Extension. Como criar um widget simples para o Today Notification.

**Comment by renatosarro** [comment]
Pessoal, submeti meu post para revisão... faltam os vídeos que farei entre hoje e amanhã, mas se quiserem adiantar a revisão, está lá... ah, as imagens não estão aparecendo, devo ter feito algo errado hehehe

**Comment by barbosa** [comment]
@renatosarro era pra ter feito um Pull Request ao invés de comitar direto no `master`.

E a data está com a data de hoje, ou seja, o artigo foi publicado :)

http://equinocios.com/ios/2016/03/22/app-extension-today-widget/

**Comment by renatosarro** [comment]
NAAAAAO :fearful:

**Comment by renatosarro** [comment]
pronto... tirei do ar hehehe
