### ISSUE TITLE
[26/03/2016] Criando frameworks universais

### ISSUE THREAD

**Issue by gsampaio** [CocoaHeadsBrasil/equinociOS#73]
O artigo irá abordar:
- Criação de um framework multiplataforma (iOS/tvOS/watchOS)
- Distribuição de frameworks tanto com Carthage e CocoaPods
- Ferramentas de qualidade de código para rodar em cima do seu framework

**Comment by marcelofabri** [comment]
Cocoapods > CocoaPods :cop:

**Comment by gsampaio** [comment]
Corrigido @marcelofabri

**Comment by brunokoga** [comment]
@gsampaio coloca lá no README também já, por favor!: )
