### ISSUE TITLE
[29/03/2016] Reactivecocoa + MVVM

### ISSUE THREAD

**Issue by delarge77** [CocoaHeadsBrasil/equinociOS#9]
Pretendo abordar : 
- O que é Reactivecocoa
- MVVM , o que é e pq utilizar ?
- MVVM e binding de dados .
- Vantagens e exemplos de como utilizar reactivecocoa em arquiteturas de projetos com MVVM

**Comment by gfpoliva** [comment]
Depois coloca a data do post @delarge77!

**Comment by delarge77** [comment]
Feito @gabrieloliva
